/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Constant: typeof import('./src/components/formulation/parts/Constant.vue')['default']
    DatapointGuide: typeof import('./src/components/panels/DatapointGuide.vue')['default']
    DatapointInterpolation: typeof import('./src/components/panels/DatapointInterpolation.vue')['default']
    DatapointSearch: typeof import('./src/components/panels/DatapointSearch.vue')['default']
    Formulation: typeof import('./src/components/formulation/Formulation.vue')['default']
    Input: typeof import('./src/components/formulation/parts/Input.vue')['default']
    InterpolationPanels: typeof import('./src/components/panels/InterpolationPanels.vue')['default']
    IntOverview: typeof import('./src/components/interpolation/IntOverview.vue')['default']
    IntSingleOut: typeof import('./src/components/interpolation/IntSingleOut.vue')['default']
    Loading: typeof import('./src/components/ui/Loading.vue')['default']
    NaryOp: typeof import('./src/components/formulation/parts/NaryOp.vue')['default']
    Overview: typeof import('./src/components/adjuster/Overview.vue')['default']
    Panels: typeof import('./src/components/Panels.vue')['default']
    PlotsOverview: typeof import('./src/components/PlotsOverview.vue')['default']
    ReducedDimPlot: typeof import('./src/components/ReducedDimPlot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleAdj: typeof import('./src/components/adjuster/SingleAdj.vue')['default']
    SingleOut: typeof import('./src/components/adjuster/SingleOut.vue')['default']
    SpyderChart: typeof import('./src/components/spyder/SpyderChart.vue')['default']
  }
}
