elements = [
    "Al",
    "Si",
    "Cu",
    "Ni",
    "Mg",
    "Mn",
    "Fe",
    "Cr",
    "Ti",
    "Zr",
    "V",
    "Zn",
]
phase_formations = [
    "Vf_FCC_A1",
    "Vf_DIAMOND_A4",
    "Vf_AL15SI2M4",
    "Vf_AL3X",
    "Vf_AL6MN",
    "Vf_MG2ZN3",
    "Vf_AL3NI2",
    "Vf_AL3NI_D011",
    "Vf_AL7CU4NI",
    "Vf_AL2CU_C16",
    "Vf_Q_ALCUMGSI",
    "Vf_AL7CU2FE",
    "Vf_MG2SI_C1",
    "Vf_AL9FE2SI2",
    "Vf_AL18FE2MG7SI10",
]
phase_temps = [
    "T_FCC_A1",
    "T_DIAMOND_A4",
    "T_AL15SI2M4",
    "T_AL3X",
    "T_AL6MN",
    "T_MG2ZN3",
    "T_AL3NI2",
    "T_AL3NI_D011",
    "T_AL7CU4NI",
    "T_AL2CU_C16",
    "T_Q_ALCUMGSI",
    "T_AL7CU2FE",
    "T_MG2SI_C1",
    "T_AL9FE2SI2",
    "T_AL18FE2MG7SI10",
    "T(liqu)",
    "T(sol)",
]
deltas = [
    "delta_T",
    "delta_T_FCC",
    "delta_T_Al15Si2M4",
    "delta_T_Si",
]
physical_properties = [
    "CSC",
    "YS(MPa)",
    "hardness(Vickers)",
    "CTEvol(1/K)(20.0-300.0�C)",
    "Density(g/cm3)",
    "Volume(m3/mol)",
    "El.conductivity(S/m)",
    "El. resistivity(ohm m)",
    "heat capacity(J/(mol K))",
    "Therm.conductivity(W/(mK))",
    "Therm. diffusivity(m2/s)",
    "Therm.resistivity(mK/W)",
    "Linear thermal expansion (1/K)(20.0-300.0�C)",
    "Technical thermal expansion (1/K)(20.0-300.0�C)",
]
input_types = ["KS1295[%]", "6082[%]", "2024[%]", "bat-box[%]", "3003[%]", "4032[%]"]
column_types = {
    "input_types": input_types,
    "elements": elements,
    # "phase_formations": phase_formations,
    # "phase_temps": phase_temps,
    # "deltas": deltas,
    "physical_properties": physical_properties,
    "full": elements + phase_formations + phase_temps + deltas + physical_properties,
}
