/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DatapointSearch: typeof import('./src/components/spyder/DatapointSearch.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PlotsOverview: typeof import('./src/components/PlotsOverview.vue')['default']
    ReducedDimPlot: typeof import('./src/components/ReducedDimPlot.vue')['default']
    SpyderChart: typeof import('./src/components/spyder/SpyderChart.vue')['default']
  }
}
